### ISSUE TITLE
Milestone 2 Feedback: Mechanics

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_group_401#31]
- [x] Directory structure is not appropriate. For example, a folder in the `src` folder should not be named `data`. I understand you mean those are scripts related to data, but still, it is confusing. Rework on your directory structure and names. Also, make sure your report is not stored in the src folder. If confused, go over [this reading](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424) provided in your course repo.
- [x] Update your README in a way that the README is the landing page of your analysis, i.e. an introduction to your project. You can remove detailed information about the analysis since these are already included in the report. You should just have a link to the report on the README.
- [x] Please list chromedriver in your dependencies

**Comment by singh-karanpal** [comment]
We have made the following changes as requested and suggested by TA:
- Re-Worked Directory Structure
- Updated README
- Added `chromedriver` in dependencies

Closing this issue.
