### ISSUE TITLE
Milestone 2 Feedback: Reasoning

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_group_401#33]
Overall, great job! Here are some improvement points:

- [x] In your report, I would suggest providing a small paragraph explaining the motivation behind your main question (I know the motivation is a bit obvious, but it is always the better practice to provide a clear explanation of the motivation behind your question). In other words, why should someone care about the question and the analysis to answer it?
- [x] I would suggest having the following main titles: Summary(or Abstract), Introduction, Data, Empirical Analysis (or Methodology), Results, Limitations and Future Directions (these could be separate as well).
- [x] Try to provide more critique of the analysis such as limitations, assumptions, etc You have mentioned these, but not really explained.

**Comment by singh-karanpal** [comment]
@Nazliozum ,

We have addressed all of the TA feedbacks and Peer feedbacks for milestone 3. At this point in time, we have updated README, Makefile, Usage Scripts, Dependencies and all minor changes sugggested by peers and TA's.

I am going ahead and closing this issue for now. We have learnt a lot in this release.
We really appreciate your valuable feedback.

Thanks & Regards
TEAM-401
